FROM postgres:13.2-alpine

ENV POSTGRES_DB lenderservice-db
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD password

# docker build -t lenderservice-image .
# docker run --name lenderservice-container -p 5433:5432 -d lenderservice-image
