FROM postgres:13.2-alpine

ENV POSTGRES_DB loanservice-db
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD password

# docker build -t loanservice-image .
# docker run --name loanservice-container -p 5435:5432 -d loanservice-image
