FROM postgres:13.2-alpine

ENV POSTGRES_DB borrowerservice-db
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD password

# docker build -t borrowerservice-image .
# docker run --name borrowerservice-container -p 5434:5432 -d borrowerservice-image
