FROM postgres:13.2-alpine

ENV POSTGRES_DB userservice-db
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD password

# docker build -t userservice-image .
# docker run --name userservice-container -p 5432:5432 -d userservice-image
